### ISSUE TITLE
Error for articles with OA in academia.edu

### ISSUE THREAD

**Issue by moqri** [Impactstory/unpaywall#12] opened 2017-05-03 20:53 UTC
Example: http://www.sciencedirect.com/science/article/pii/S0361368201000277
open url: http://www.academia.edu/download/36140325/1-s2.0-S0361368201000277-main.pdf
Error: Page Not Found. Sorry. We can't find the page you're looking for.

If you are logged into the academia.edu website you do not see the error message (will be redirected to the correct url)

**Comment by ashander** [comment] 2017-05-17 00:24
duplicate of #8

**Closed** 2017-05-17 00:25 UTC
