### ISSUE TITLE
Redirect from one paywall to another paywall (INFORMS to JSTOR)

### ISSUE THREAD

**Issue by moqri** [Impactstory/unpaywall#13] opened 2017-05-03 20:53 UTC
Example: http://pubsonline.informs.org/doi/abs/10.1287/isre.2.3.173
Redirects to: http://www.jstor.org/stable/23010882

**Comment by eocarragain** [comment] 2017-05-17 14:28
Google Scholar seems to be the culprit here. Perhaps certain domains (like jstor.org) should be filtered if returned by GS?

GS (jstor link): https://api.oadoi.org/gs/cache/10.1287/isre.2.3.173

OADOI (no fulltext): https://api.oadoi.org/10.1287/isre.2.3.173

**Comment by ioverka** [comment] 2017-09-13 16:42
Cannot reproduce this issue any longer.

**Comment by richard-orr** [comment] 2019-08-09 19:29
Closing as the involved functionality no longer exists. https://api.oadoi.org/gs/cache/10.1287/isre.2.3.173?email=richard@unpaywall.org and https://api.oadoi.org/10.1287/isre.2.3.173?email=richard@unpaywall.org are handled identically and do not involve Google Scholar.

**Closed by richard-orr** 2019-08-09 19:29 UTC
