### ISSUE TITLE
Saying available when it is really not

### ISSUE THREAD

**Issue by moqri** [Impactstory/unpaywall#14] opened 2017-05-15 19:37 UTC
https://openaccessbutton.org/?url=http%3A%2F%2Fdx.doi.org%2F10.1287%2Fisre.2015.0618

**Comment by eocarragain** [comment] 2017-05-17 09:38
Confirmed. I can't access the pdf either.

OA Button has it wrong:
https://api.openaccessbutton.org/availability?url=http%3A%2F%2Fdx.doi.org%2F10.1287%2Fisre.2015.0618

Google Scholar (and unpaywall plugin) has it wrong:
https://api.oadoi.org/gs/cache/10.1287/isre.2015.0618

OADOI has it correct:
https://api.oadoi.org/10.1287/isre.2015.0618

**Comment by richard-orr** [comment] 2019-08-09 19:34
Closing because the Unpaywall database no longer has an open location for this DOI.

**Closed by richard-orr** 2019-08-09 19:34 UTC
